### ISSUE TITLE
Many buggy states with SSO login status and whether I can see my puppets and or projects

### ISSUE THREAD

**Issue by batchku** [irllabs/dranimate#10] opened 2021-08-23 04:10 UTC
Many buggy states with SSO login status and whether I can see my puppets and or projects

**Comment by lazarmitic** [comment] 2021-08-24 10:11
I can't reproduce this issue - if you run into it again, please post detailed reproduction steps. Closing for now, reopen if needed.

**Closed as completed by lazarmitic** 2021-08-24 10:11 UTC
Labels: bug, lazar-100, can't reproduce
